name: Build and release Aseprite for Windows

on:
  push:
    branches:
      - main
    paths:
      - 'BuildLog.md'
  workflow_dispatch:
env:
  BUILD_TYPE: Release

jobs:
  fetch-aseprite-info:
    name: Fetch deps info
    runs-on: ubuntu-latest
    outputs:
      download-link: ${{ steps.aseprite-link.outputs.download-link }}
      release-tag: ${{ steps.aseprite-link.outputs.release-tag }}
    steps:
      - name: Fetch Aseprite release link
        id: aseprite-link
        uses: a1393323447/fetch-release@main
        with:
            group: aseprite
            repo: aseprite
            match: Aseprite-.*?-Source.zip

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: fetch-aseprite-info
    permissions:
      contents: write
    outputs:
      download-link: ${{ needs.fetch-aseprite-info.outputs.download-link }}
      release-tag: ${{ needs.fetch-aseprite-info.outputs.release-tag }}
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.fetch-aseprite-info.outputs.release-tag }}
          body: Aseprite-${{ needs.fetch-aseprite-info.outputs.release-tag }} for Windows
          skipIfReleaseExists: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-aseprite-windows:
    name: Build Aseprite for Windows
    needs: create-release
    permissions:
      contents: write
    runs-on: windows-latest
    
    steps:
      - name: Install wget
        shell: powershell
        run: choco install wget -y --no-progress
          
      - uses: actions/checkout@v4
      
      - name: Install Aseprite
        shell: bash
        run: |
          git clone --recurse-submodules -j8 https://github.com/aseprite/aseprite --branch ${{ needs.create-release.outputs.release-tag }}
          
      - name: Install Skia
        working-directory: aseprite
        shell: bash
        run: |
          wget https://github.com/aseprite/skia/releases/download/m124-08a5439a6b/Skia-Windows-Release-x64.zip
          unzip Skia-Windows-Release-x64.zip -d skia
          
      - uses: aseprite/get-ninja@main
      - uses: ilammy/msvc-dev-cmd@v1
        
      - name: Generating Makefiles
        shell: bash
        working-directory: aseprite
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_TESTS=OFF \
            -DENABLE_SCRIPTING=on \
            -DENABLE_CCACHE=off \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR=$(realpath skia) \
            -DOPENSSL_USE_STATIC_LIBS=ON \
            -DSKIA_LIBRARY_DIR=$(realpath skia/out/Release-x64)
            
      - name: Compiling
        shell: bash
        working-directory: aseprite
        run: |
          cd build && ninja
          
      - name: Create portable package
        shell: bash
        working-directory: aseprite/build/bin
        run: |
          # 创建便携版配置文件
          echo '# This file is here so Aseprite behaves as a portable program' > aseprite.ini
          # 创建ZIP压缩包
          7z a Aseprite-${{ needs.create-release.outputs.release-tag }}-Windows.zip *
          
      - name: Upload Windows package
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: aseprite/build/bin/Aseprite-${{ needs.create-release.outputs.release-tag }}-Windows.zip
          asset_name: Aseprite-${{ needs.create-release.outputs.release-tag }}-Windows.zip
          tag: ${{ needs.create-release.outputs.release-tag }}
